### ISSUE TITLE
StringIndexOutOfBoundsException with scm provider jar

### ISSUE THREAD

**Issue by mosabua** [simpligility/maven-repository-tools#23]
org.apache.maven.scm:maven-scm-provider-clearcase:jar:1.9.2
 
 
09:30:44.569 [main] INFO  LoggingRepositoryListener - Resolved artifact org.apache.maven.scm:maven-scm-api:jar:javadoc:1
.9.2 from central (http://mavenrepository.tsl.telus.com/nexus/content/groups/telus-unauthorized, default, releases+snaps
hots)
09:30:44.569 [main] INFO  ArtifactRetriever - Retrieved c:\tools\maven-repository-provisioner\local-repo\org\apache\mave
n\scm\maven-scm-api\1.9.2\maven-scm-api-1.9.2-javadoc.jar
09:30:44.569 [main] INFO  LoggingRepositoryListener - Resolving artifact org.codehaus.plexus:plexus-utils:jar:javadoc:3.
0.15
09:30:44.569 [main] INFO  LoggingRepositoryListener - Resolved artifact org.codehaus.plexus:plexus-utils:jar:javadoc:3.0
.15 from central (http://mavenrepository.tsl.telus.com/nexus/content/groups/telus-unauthorized, default, releases+snapsh
ots)
09:30:44.569 [main] INFO  ArtifactRetriever - Retrieved c:\tools\maven-repository-provisioner\local-repo\org\codehaus\pl
exus\plexus-utils\3.0.15\plexus-utils-3.0.15-javadoc.jar
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911)
        at com.simpligility.maven.provisioner.GavUtil.getGavFromRepositoryPath(GavUtil.java:11)
        at com.simpligility.maven.provisioner.MavenRepositoryHelper.deployToRemote(MavenRepositoryHelper.java:61)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.main(MavenRepositoryProvisioner.java:64)

**Comment by mosabua** [comment]
This works now.

**Comment by mosabua** [comment]
Use a newer release - it works now (and has for quite a while).
