### ISSUE TITLE
Failed to fetch classifier & extensions 

### ISSUE THREAD

**Issue by nsteinmetz** [simpligility/maven-repository-tools#43]
Hi,

Aside our traditional jars, we also publish files using `zip` extension and `static` classifier from maven assembly.

```shell
java -jar  maven-repository-provisioner-1.3.1-jar-with-dependencies.jar -it true -ip true -ij true -ir true -is true -a "net.bigcorp.thirdparty:product-catalog:zip:static:1.296" -su deployment -sp [REDACTED] -s "https://repository.admin.bigcorp.net/repository/releases" -t "https://nexus.bigcorp.net/repository/releases" -u deployment -p [REDACTED]
16:05:41.204 [main] INFO  MavenRepositoryProvisioner - -----------------------------------
16:05:41.206 [main] INFO  MavenRepositoryProvisioner -  Maven Repository Provisioner
16:05:41.206 [main] INFO  MavenRepositoryProvisioner -  simpligility technologies inc.
16:05:41.207 [main] INFO  MavenRepositoryProvisioner -  http://www.simpligility.com
16:05:41.207 [main] INFO  MavenRepositoryProvisioner - -----------------------------------
16:05:41.249 [main] INFO  MavenRepositoryProvisioner -
Provisioning artifacts: net.bigcorp.thirdparty:product-catalog:zip:static:1.296
Source: https://repository.admin.bigcorp.net/repository/releases
Target: https://nexus.bigcorp.net/repository/releases/
Username: deployment
Password: ***************************************
IncludeSources: true
IncludeJavadoc: true
IncludeProvidedScope: true
IncludeTestScope: true
IncludeRuntimeScope: true
Check target: true
Verify only: false
Local cache or source repository directory: local-cache


16:05:41.249 [main] INFO  MavenRepositoryProvisioner -  Absolute path: /Users/nsteinmetz/Documents/Clients/bigcorp/bigcorp-ops/ansible/roles/LF.nexus/files/local-cache
16:05:41.249 [main] INFO  MavenRepositoryProvisioner - Detected local cache directory 'local-cache'.
16:05:41.249 [main] INFO  MavenRepositoryProvisioner - Artifact coordinates specified - removing stale cache directory from prior execution.
16:05:41.277 [main] INFO  MavenRepositoryProvisioner - local-cache deleted.
16:05:41.317 [main] INFO  MavenRepositoryProvisioner - Artifact retrieval starting.
16:05:41.597 [main] INFO  LoggingRepositoryListener - Resolving artifact net.bigcorp.thirdparty:product-catalog:pom:1.296
16:05:41.600 [main] INFO  LoggingRepositoryListener - Downloading artifact net.bigcorp.thirdparty:product-catalog:pom:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.008 [main] INFO  LoggingTransferListener - Downloading: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296.pom
16:05:42.267 [main] INFO  LoggingTransferListener - Downloaded: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296.pom (4 KB at 14.9 KB/sec)
16:05:42.280 [main] INFO  LoggingRepositoryListener - Downloaded artifact net.bigcorp.thirdparty:product-catalog:pom:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.281 [main] INFO  LoggingRepositoryListener - Resolved artifact net.bigcorp.thirdparty:product-catalog:pom:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.322 [main] INFO  LoggingRepositoryListener - Resolving artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT
16:05:42.324 [main] INFO  LoggingRepositoryListener - Resolving metadata net.bigcorp.thirdparty:product-catalog-parent:3.1-SNAPSHOT/maven-metadata.xml from /Users/nsteinmetz/Documents/Clients/bigcorp/bigcorp-ops/ansible/roles/LF.nexus/files/local-cache (enhanced)
16:05:42.325 [main] INFO  LoggingRepositoryListener - Resolved metadata net.bigcorp.thirdparty:product-catalog-parent:3.1-SNAPSHOT/maven-metadata.xml from /Users/nsteinmetz/Documents/Clients/bigcorp/bigcorp-ops/ansible/roles/LF.nexus/files/local-cache (enhanced)
16:05:42.371 [main] INFO  LoggingRepositoryListener - Resolving metadata net.bigcorp.thirdparty:product-catalog-parent:3.1-SNAPSHOT/maven-metadata.xml from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.381 [main] INFO  LoggingTransferListener - Downloading: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog-parent/3.1-SNAPSHOT/maven-metadata.xml
16:05:42.525 [main] INFO  LoggingRepositoryListener - Resolved metadata net.bigcorp.thirdparty:product-catalog-parent:3.1-SNAPSHOT/maven-metadata.xml from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.525 [main] INFO  LoggingRepositoryListener - Downloading artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.527 [main] INFO  LoggingTransferListener - Downloading: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog-parent/3.1-SNAPSHOT/product-catalog-parent-3.1-SNAPSHOT.pom
16:05:42.649 [main] INFO  LoggingTransferListener - Could not transfer artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from/to central (https://repository.admin.bigcorp.net/repository/releases): Bad Request (400)
16:05:42.650 [main] INFO  LoggingRepositoryListener - Downloaded artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.652 [main] INFO  LoggingRepositoryListener - Resolved artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from null
16:05:42.656 [main] INFO  ArtifactRetriever - DependencyResolutionException
org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for net.bigcorp.thirdparty:product-catalog:zip:static:1.296
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:351)
        at com.simpligility.maven.provisioner.ArtifactRetriever.getArtifactResults(ArtifactRetriever.java:165)
        at com.simpligility.maven.provisioner.ArtifactRetriever.retrieve(ArtifactRetriever.java:95)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.retrieveArtifacts(MavenRepositoryProvisioner.java:122)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.main(MavenRepositoryProvisioner.java:68)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for net.bigcorp.thirdparty:product-catalog:zip:static:1.296
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:208)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:307)
        ... 4 common frames omitted
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for net.bigcorp.thirdparty:product-catalog:zip:static:1.296
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:323)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:192)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
        ... 5 common frames omitted
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from/to central (https://repository.admin.bigcorp.net/repository/releases): Bad Request (400)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:178)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:224)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1051)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:314)
        ... 7 common frames omitted
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from/to central (https://repository.admin.bigcorp.net/repository/releases): Bad Request (400)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:174)
        ... 12 common frames omitted
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact net.bigcorp.thirdparty:product-catalog-parent:pom:3.1-SNAPSHOT from/to central (https://repository.admin.bigcorp.net/repository/releases): Bad Request (400)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
        ... 15 common frames omitted
Caused by: org.apache.http.client.HttpResponseException: Bad Request (400)
        at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:475)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:300)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:252)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
        ... 20 common frames omitted
16:05:42.759 [main] INFO  ArtifactRetriever - Processing POM file /Users/nsteinmetz/Documents/Clients/bigcorp/bigcorp-ops/ansible/roles/LF.nexus/files/local-cache/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296.pom
16:05:42.764 [main] INFO  LoggingRepositoryListener - Resolving artifact net.bigcorp.thirdparty:product-catalog:jar:1.296
16:05:42.764 [main] INFO  LoggingRepositoryListener - Downloading artifact net.bigcorp.thirdparty:product-catalog:jar:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:42.765 [main] INFO  LoggingTransferListener - Downloading: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296.jar
16:05:43.094 [main] INFO  LoggingTransferListener - Downloaded: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296.jar (2783 KB at 8458.5 KB/sec)
16:05:43.096 [main] INFO  LoggingRepositoryListener - Downloaded artifact net.bigcorp.thirdparty:product-catalog:jar:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.096 [main] INFO  LoggingRepositoryListener - Resolved artifact net.bigcorp.thirdparty:product-catalog:jar:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.096 [main] INFO  ArtifactRetriever - Retrieved /Users/nsteinmetz/Documents/Clients/bigcorp/bigcorp-ops/ansible/roles/LF.nexus/files/local-cache/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296.jar
16:05:43.096 [main] INFO  LoggingRepositoryListener - Resolving artifact net.bigcorp.thirdparty:product-catalog:jar:sources:1.296
16:05:43.097 [main] INFO  LoggingRepositoryListener - Downloading artifact net.bigcorp.thirdparty:product-catalog:jar:sources:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.098 [main] INFO  LoggingTransferListener - Downloading: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296-sources.jar
16:05:43.258 [main] INFO  LoggingTransferListener - Downloaded: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296-sources.jar (275 KB at 1715.6 KB/sec)
16:05:43.260 [main] INFO  LoggingRepositoryListener - Downloaded artifact net.bigcorp.thirdparty:product-catalog:jar:sources:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.260 [main] INFO  LoggingRepositoryListener - Resolved artifact net.bigcorp.thirdparty:product-catalog:jar:sources:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.260 [main] INFO  ArtifactRetriever - Retrieved /Users/nsteinmetz/Documents/Clients/bigcorp/bigcorp-ops/ansible/roles/LF.nexus/files/local-cache/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296-sources.jar
16:05:43.260 [main] INFO  LoggingRepositoryListener - Resolving artifact net.bigcorp.thirdparty:product-catalog:jar:javadoc:1.296
16:05:43.261 [main] INFO  LoggingRepositoryListener - Downloading artifact net.bigcorp.thirdparty:product-catalog:jar:javadoc:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.262 [main] INFO  LoggingTransferListener - Downloading: https://repository.admin.bigcorp.net/repository/releases/net/bigcorp/thirdparty/product-catalog/1.296/product-catalog-1.296-javadoc.jar
16:05:43.385 [main] INFO  LoggingTransferListener - Could not find artifact net.bigcorp.thirdparty:product-catalog:jar:javadoc:1.296 in central (https://repository.admin.bigcorp.net/repository/releases)
16:05:43.385 [main] INFO  LoggingRepositoryListener - Downloaded artifact net.bigcorp.thirdparty:product-catalog:jar:javadoc:1.296 from central (https://repository.admin.bigcorp.net/repository/releases, default, releases+snapshots)
16:05:43.385 [main] INFO  LoggingRepositoryListener - Resolved artifact net.bigcorp.thirdparty:product-catalog:jar:javadoc:1.296 from null
16:05:43.385 [main] INFO  ArtifactRetriever - ArtifactResolutionException when retrieving net.bigcorp.thirdparty:product-catalog:1.296 with javadoc
16:05:43.385 [main] INFO  MavenRepositoryProvisioner - Artifact retrieval completed.
16:05:43.385 [main] INFO  MavenRepositoryProvisioner - Artifact deployment starting.
16:05:43.533 [main] INFO  MavenRepositoryHelper - Found POM for net.bigcorp.thirdparty:product-catalog:1.296 already in target. Skipping deployment.
16:05:43.595 [main] INFO  MavenRepositoryProvisioner - Artifact deployment completed.
16:05:43.595 [main] INFO  MavenRepositoryProvisioner - Processing Completed.
16:05:43.596 [main] INFO  MavenRepositoryProvisioner -
Processing Summary
-----------------------------------
Configuration:

Provisioning artifacts: net.bigcorp.thirdparty:product-catalog:zip:static:1.296
Source: https://repository.admin.bigcorp.net/repository/releases
Target: https://nexus.bigcorp.net/repository/releases/
Username: deployment
Password: ***************************************
IncludeSources: true
IncludeJavadoc: true
IncludeProvidedScope: true
IncludeTestScope: true
IncludeRuntimeScope: true
Check target: true
Verify only: false
Local cache or source repository directory: local-cache

Sucessful Retrievals:

net.bigcorp.thirdparty:product-catalog:jar:1.296
net.bigcorp.thirdparty:product-catalog:jar:sources:1.296

Failed Retrievals:

Could not find artifact net.bigcorp.thirdparty:product-catalog:jar:javadoc:1.296 in central (https://repository.admin.bigcorp.net/repository/releases)
Failed to read artifact descriptor for net.bigcorp.thirdparty:product-catalog:zip:static:1.296

Sucessful Deployments:

Failed Deployments:

Skipped Deployments (POM already in target):

net.bigcorp.thirdparty:product-catalog:1.296

Potential Deployments :

16:05:43.619 [main] INFO  MavenRepositoryProvisioner - Exiting: SUCCESS
Failed to retrieve some artifacts.
Deployment completed successfully.
```

I'm not a java dev but from what I saw, this case is not managed. 

From what I understand and I may be wrong:
* Your GAV object is just about groupid, artefact, packaging (few use cases managed) and version
* I don't see how classifier and version are extracted from the `-a` parameter
* You only support the main cases (jar + javadoc + test + sources) for my packaging.

How could I add the missing parameters ? 

Thanks,
Nicolas

**Comment by mosabua** [comment]
they are supported.. and I just added support for zip .. check out the test cases for aar and such

**Comment by nsteinmetz** [comment]
Thnkas !

**Comment by mosabua** [comment]
I will work towards a full release in the next week or two as well.
