### ISSUE TITLE
Unable to start because of guice bounding errors

### ISSUE THREAD

**Issue by dzwicker** [simpligility/maven-repository-tools#54]
If I start the tool I get `No implementation for org.apache.maven.model.composition.DependencyManagementImporter was bound.` error message.

**Comment by mosabua** [comment]
You must be starting it wrong. Here are the instructions. I just tried again with 1.4.1 ,, 

https://github.com/simpligility/maven-repository-tools/tree/master/maven-repository-provisioner#usage

$ java -jar maven-repository-provisioner-1.4.1-jar-with-dependencies.jar

https://repo1.maven.org/maven2/com/simpligility/maven/maven-repository-provisioner/1.4.1/

**Comment by MikeMikeNorthLane** [comment]
I'm running into the same problems.  However I am running the jar after manually building from command line.
The tool doesn't seem to support HTTP headers for GitLab authorization so I was trying to force the HTTP headers in the source code...  I get about 16 different errors of the same kind below:

1) No implementation for org.apache.maven.model.composition.DependencyManagementImporter was bound.
  while locating org.apache.maven.model.composition.DependencyManagementImporter
    for field at org.apache.maven.model.building.DefaultModelBuilder.dependencyManagementImporter(DefaultModelBuilder.java:207)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

2) No implementation for org.apache.maven.model.management.DependencyManagementInjector was bound.
  while locating org.apache.maven.model.management.DependencyManagementInjector
    for field at org.apache.maven.model.building.DefaultModelBuilder.dependencyManagementInjector(DefaultModelBuilder.java:213)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

3) No implementation for org.apache.maven.model.inheritance.InheritanceAssembler was bound.
  while locating org.apache.maven.model.inheritance.InheritanceAssembler
    for field at org.apache.maven.model.building.DefaultModelBuilder.inheritanceAssembler(DefaultModelBuilder.java:201)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

**Comment by mosabua** [comment]
Did you download the right file .. you need to download the executable jar...

**Comment by MikeMikeNorthLane** [comment]
Again, the downloadable "runs" fine, however there is a limitation in the source code that doesn't allow custom HTTP headers.   I am downloading the source code, compiling and trying to run from the locally compiled source (which doesn't run with the errors originally noted above)..    Stated differently: We can't use the downloadable .jar because the current downloadable jar doesn't support custom HTTP headers on the target repository...

**Comment by MikeMikeNorthLane** [comment]
Can't quite modify source code if I can't get it to run. ;)
