### ISSUE TITLE
Cannot run .jar file using test.sh, Guice creation errors

### ISSUE THREAD

**Issue by MikeMikeNorthLane** [simpligility/maven-repository-tools#56]
1) Download source
2) mvn clean install
3) ./test.sh

ERRORS at most basic level trying to run the jar:
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) No implementation for org.apache.maven.model.composition.DependencyManagementImporter was bound.
  while locating org.apache.maven.model.composition.DependencyManagementImporter
    for field at org.apache.maven.model.building.DefaultModelBuilder.dependencyManagementImporter(DefaultModelBuilder.java:207)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

2) No implementation for org.apache.maven.model.management.DependencyManagementInjector was bound.
  while locating org.apache.maven.model.management.DependencyManagementInjector
    for field at org.apache.maven.model.building.DefaultModelBuilder.dependencyManagementInjector(DefaultModelBuilder.java:213)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

3) No implementation for org.apache.maven.model.inheritance.InheritanceAssembler was bound.
  while locating org.apache.maven.model.inheritance.InheritanceAssembler
    for field at org.apache.maven.model.building.DefaultModelBuilder.inheritanceAssembler(DefaultModelBuilder.java:201)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

4) No implementation for org.apache.maven.model.plugin.LifecycleBindingsInjector was bound.
  while locating org.apache.maven.model.plugin.LifecycleBindingsInjector
    for field at org.apache.maven.model.building.DefaultModelBuilder.lifecycleBindingsInjector(DefaultModelBuilder.java:219)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

5) No implementation for org.apache.maven.model.interpolation.ModelInterpolator was bound.
  while locating org.apache.maven.model.interpolation.ModelInterpolator
    for field at org.apache.maven.model.building.DefaultModelBuilder.modelInterpolator(DefaultModelBuilder.java:165)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

6) No implementation for org.apache.maven.model.normalization.ModelNormalizer was bound.
  while locating org.apache.maven.model.normalization.ModelNormalizer
    for field at org.apache.maven.model.building.DefaultModelBuilder.modelNormalizer(DefaultModelBuilder.java:159)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

7) No implementation for org.apache.maven.model.path.ModelPathTranslator was bound.
  while locating org.apache.maven.model.path.ModelPathTranslator
    for field at org.apache.maven.model.building.DefaultModelBuilder.modelPathTranslator(DefaultModelBuilder.java:171)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

8) No implementation for org.apache.maven.model.building.ModelProcessor was bound.
  while locating org.apache.maven.model.building.ModelProcessor
    for field at org.apache.maven.model.building.DefaultModelBuilder.modelProcessor(DefaultModelBuilder.java:147)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

9) No implementation for org.apache.maven.model.path.ModelUrlNormalizer was bound.
  while locating org.apache.maven.model.path.ModelUrlNormalizer
    for field at org.apache.maven.model.building.DefaultModelBuilder.modelUrlNormalizer(DefaultModelBuilder.java:177)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

10) No implementation for org.apache.maven.model.validation.ModelValidator was bound.
  while locating org.apache.maven.model.validation.ModelValidator
    for field at org.apache.maven.model.building.DefaultModelBuilder.modelValidator(DefaultModelBuilder.java:153)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

11) No implementation for org.apache.maven.model.plugin.PluginConfigurationExpander was bound.
  while locating org.apache.maven.model.plugin.PluginConfigurationExpander
    for field at org.apache.maven.model.building.DefaultModelBuilder.pluginConfigurationExpander(DefaultModelBuilder.java:225)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

12) No implementation for org.apache.maven.model.management.PluginManagementInjector was bound.
  while locating org.apache.maven.model.management.PluginManagementInjector
    for field at org.apache.maven.model.building.DefaultModelBuilder.pluginManagementInjector(DefaultModelBuilder.java:231)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

13) No implementation for org.apache.maven.model.profile.ProfileInjector was bound.
  while locating org.apache.maven.model.profile.ProfileInjector
    for field at org.apache.maven.model.building.DefaultModelBuilder.profileInjector(DefaultModelBuilder.java:195)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

14) No implementation for org.apache.maven.model.profile.ProfileSelector was bound.
  while locating org.apache.maven.model.profile.ProfileSelector
    for field at org.apache.maven.model.building.DefaultModelBuilder.profileSelector(DefaultModelBuilder.java:189)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

15) No implementation for org.apache.maven.model.plugin.ReportConfigurationExpander was bound.
  while locating org.apache.maven.model.plugin.ReportConfigurationExpander
    for field at org.apache.maven.model.building.DefaultModelBuilder.reportConfigurationExpander(DefaultModelBuilder.java:237)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

16) No implementation for org.apache.maven.model.plugin.ReportingConverter was bound.
  while locating org.apache.maven.model.plugin.ReportingConverter
    for field at org.apache.maven.model.building.DefaultModelBuilder.reportingConverter(DefaultModelBuilder.java:243)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

17) No implementation for org.apache.maven.model.superpom.SuperPomProvider was bound.
  while locating org.apache.maven.model.superpom.SuperPomProvider
    for field at org.apache.maven.model.building.DefaultModelBuilder.superPomProvider(DefaultModelBuilder.java:183)
  at org.apache.maven.repository.internal.MavenResolverModule.configure(MavenResolverModule.java:58)

17 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.simpligility.maven.provisioner.RepositoryHandler.newRepositorySystem(RepositoryHandler.java:46)
        at com.simpligility.maven.provisioner.RepositoryHandler.getRepositorySystem(RepositoryHandler.java:39)
        at com.simpligility.maven.provisioner.ArtifactRetriever.initialize(ArtifactRetriever.java:75)
        at com.simpligility.maven.provisioner.ArtifactRetriever.<init>(ArtifactRetriever.java:70)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.retrieveArtifacts(MavenRepositoryProvisioner.java:121)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.main(MavenRepositoryProvisioner.java:68)

**Comment by mosabua** [comment]
I can not reproduce this .. it always worked for me. Nevertheless ... we just merged a bunch of improvements so please try again .
