### ISSUE TITLE
Jar with dependencies is incomplete

### ISSUE THREAD

**Issue by SebastianFlothow** [simpligility/maven-repository-tools#86]
In `maven-repository-provisioner-1.5.1-jar-with-dependencies.jar`, the class `javax.annotation.PostConstruct` is missing (and possibly others from that package), making it necessary to manually provide `javax.annotation-api-1.3.2.jar`. Doable of course, but it sort of defeats the point of a "with dependencies" jar. It also means that the invocation using `java -jar`, as given in `maven-repository-provisioner/README.asciidoc`, won't work.

**Comment by mosabua** [comment]
Also tried with the 1.5.1 jar from Maven Central.. also works

**Comment by SebastianFlothow** [comment]
Failure trying to deploy to a local dummy directory, using the the 1.5.1 jar from Maven Central:

```
java -jar maven-repository-provisioner-1.5.1-jar-with-dependencies.jar -t dummy
15:11:26.140 [main] INFO  MavenRepositoryProvisioner - -----------------------------------
15:11:26.156 [main] INFO  MavenRepositoryProvisioner -  Maven Repository Provisioner
15:11:26.156 [main] INFO  MavenRepositoryProvisioner -  simpligility technologies inc.
15:11:26.156 [main] INFO  MavenRepositoryProvisioner -  http://www.simpligility.com
15:11:26.156 [main] INFO  MavenRepositoryProvisioner - -----------------------------------
15:11:26.172 [main] INFO  MavenRepositoryProvisioner -
Provisioning artifacts: null
Source: https://repo.maven.apache.org/maven2
Target: file:/T:/maven-repository-provisioner/dummy
Username: null
IncludeSources: true
IncludeJavadoc: true
IncludeProvidedScope: false
IncludeTestScope: false
IncludeRuntimeScope: false
Check target: true
Verify only: false
Local cache or source repository directory: local-cache


15:11:26.172 [main] INFO  MavenRepositoryProvisioner -  Absolute path: T:\maven-repository-provisioner\local-cache
15:11:26.172 [main] INFO  MavenRepositoryProvisioner - Detected local cache directory 'local-cache'.
15:11:26.172 [main] INFO  MavenRepositoryProvisioner - No artifact coordinates specified - using cache directory as source.
15:11:26.187 [main] INFO  MavenRepositoryProvisioner - Artifact retrieval skipped.
15:11:26.187 [main] INFO  MavenRepositoryProvisioner - Artifact deployment starting.
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
        at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173)
        at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160)
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.simpligility.maven.provisioner.RepositoryHandler.newRepositorySystem(RepositoryHandler.java:54)
        at com.simpligility.maven.provisioner.RepositoryHandler.getRepositorySystem(RepositoryHandler.java:42)
        at com.simpligility.maven.provisioner.MavenRepositoryDeployer.initialize(MavenRepositoryDeployer.java:89)
        at com.simpligility.maven.provisioner.MavenRepositoryDeployer.<init>(MavenRepositoryDeployer.java:76)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.deployArtifacts(MavenRepositoryProvisioner.java:118)
        at com.simpligility.maven.provisioner.MavenRepositoryProvisioner.main(MavenRepositoryProvisioner.java:60)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
        at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:69)
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75)
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 22 more
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.sisu.bean.LifecycleBuilder.addLifecycleMethods(LifecycleBuilder.java:86)
        at org.eclipse.sisu.bean.LifecycleBuilder.build(LifecycleBuilder.java:53)
        at org.eclipse.sisu.bean.LifecycleManager.buildLifecycle(LifecycleManager.java:106)
        at org.eclipse.sisu.bean.LifecycleManager.manage(LifecycleManager.java:41)
        at org.eclipse.sisu.bean.LifecycleModule$1.matches(LifecycleModule.java:42)
        at org.eclipse.sisu.bean.LifecycleModule$1.matches(LifecycleModule.java:1)
        at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:104)
        at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:40)
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:49)
        at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 37 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 52 more
```

This is on Microsoft Windows 10 Enterprise using Java 17, full details:

```
java -version
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment Temurin-17.0.13+11 (build 17.0.13+11)
OpenJDK 64-Bit Server VM Temurin-17.0.13+11 (build 17.0.13+11, mixed mode, sharing)
```

**Comment by jjlauer** [comment]
Same error for me on various JVMs. I understand your using some sort of JVM that quite clearly has that annotation dependency built-in, but if you download a JVM from Azul, you'll be able to replicate this error.

https://www.azul.com/downloads/?package=jdk#zulu

**Comment by jjlauer** [comment]
Adding

```
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>  
</dependency>
```

to the pom.xml resolves this issue.

**Comment by bcopy** [comment]
Tried a whole set of JDK (openjdk v23, 17.0.12-oracle, 22.3.r17-graalvm) while adding the javax.annotation-api v1.3.2 JAR to the classpath - and version 1.5.2 of maven-repository-provisioner and I also obtain everytime :

`
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
    at org.eclipse.sisu.bean.LifecycleBuilder.addLifecycleMethods(LifecycleBuilder.java:86)
    at org.eclipse.sisu.bean.LifecycleBuilder.build(LifecycleBuilder.java:53)
    at org.eclipse.sisu.bean.LifecycleManager.buildLifecycle(LifecycleManager.java:106)
`

**Comment by q-dannyhyon** [comment]
Facing the same as other above, for Java 17.
